load("multiple.rdata")
require(ggplot2)
load("tomato,rdata")
require(ggplot2)
require(ggplot2)
head(diamonds)
data(diamonds)
install.packages(ggplot2, DEP = TRUE)
install.packages(ggplot2, dep = TRUE)
install.packages("ggplot2", dep = TRUE)
Require(ggplot2)
data(diamonds)
require(XML)
install.packages("XML"))
bowlPool<- readHTMLTable(theURL, which = 1, header = FALSE, stringAsFactors = FALSE)
bowlPool